### PR TITLE
add support for pointer events

### PR DESCRIPTION
**Pull request by gbagan**
Add support for pointer events
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

A PR to dom-indexed will follow.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Thanks, @gbagan. Ping me when the dom-indexed PR is ready!

**Comment by thomashoneyman** [comment]
How would you like to handle this change, @garyb, given that this is a major version upgrade to `dom-indexed`?

**Comment by garyb** [comment]
A major bump to a dependency is a major bump to a dependant... so major bump I guess! :smile:

I don't have anything else breaking just now, I don't think it's worth holding this up until we do.

**Comment by thomashoneyman** [comment]
Yea I meant in the way of handling Halogen 8, as we just released Halogen 7 last week 😅

**Comment by garyb** [comment]
I think we just make a release without any fanfare, I'm not sure if people are paying that close attention to what the big number is... I wasn't sure what number we were up to now at least :smile:

**Pull request merged**
