### PR TITLE
Replace `id_` with `id`

### PR DESCRIPTION
**Pull request by matoruru**
Hello maintainers.

I made this because I saw this comment on the guide:

https://github.com/purescript-halogen/purescript-halogen/blob/b0eee5db9081a86bcdadc6a515145e14b5e2d3ed/docs/guide/01-Rendering-Halogen-HTML.md#L68

but is this still too early?

### CODE REVIEW

**Comment by matoruru** [comment]
Sorry if you were already planned when to make it 😓

**Comment by thomashoneyman** [comment]
Hi @matoruru, thanks for this! I'm happy to add this, but we'd ideally keep `id_` around with a deprecation warning. What do you think of rebasing your changes onto the `next-6` branch, and adding a deprecation notice to the existing `id_` function? That way `id_` is deprecated in Halogen 6 and can be removed in the following version.

cc: @garyb.

For more: https://github.com/purescript/documentation/blob/master/guides/Custom-Type-Errors.md

**Comment by matoruru** [comment]
Hello. Thank you for your kind answer 😊 Yes I was actually thinking that warning for the backward compatibility. That sounds good and there's no problem with adding the warning one and `next-6`. I'll add it soon.

**Comment by thomashoneyman** [comment]
The only other thing to do would be to rebase this onto `next-6` and choose that as the base branch for the PR. We're tracking Halogen 6 (the upcoming release which will come out with PureScript 0.14) there.

**Comment by matoruru** [comment]
That was ture. I am going to rebase and push it again.

**Review by thomashoneyman — APPROVED** [review]
Thanks!

**Comment by matoruru** [comment]
Not at all!

**Comment by garyb** [comment]
🎉

**Pull request merged**
